### ISSUE TITLE
Type name of documents is not customizable

### ISSUE THREAD

**Issue by DBarthe** [appbaseio/searchbox#66]
Hello,

I plan to use searchbox over my own es cluster, but it seems that the type name is hardcoded to `_reactivesearch.v3` :  https://github.com/appbaseio/searchbox/blob/2e708b7c3c45a8c78210953d88fe3ae64cd40f90/packages/searchbase/src/SearchComponent.js#L1131
 
I'm using default es type name which is `_doc`.

Would be nice if this would be an option.

Maybe I'm missing something  ?

EDIT: I cannot change my type names to `_reactivesearch.v3`, because :
```
mapping type name [_reactivesearch.v3] can't start with '_' unless it is called [_doc]
```

**Comment by bietkul** [comment]
@DBarthe Currently, `searchbox` only supports the Appbase cluster so it is not possible to run it with any ES cluster. We have plans to make it compatible with any ES cluster.

**Comment by DBarthe** [comment]
ok thanks for answering

**Comment by iamramrana** [comment]
@bietkul I have a question related to this can we avoid this _reactivesearch.v3 type from the url ?
